# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Reload config with 'r'
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Unbind default split keys
unbind '"'
unbind '%'

# Bind new pane split keys
bind '|' split-window -h -c '#{pane_current_path}'
bind '_' split-window -v -c '#{pane_current_path}'

# set message display time. Default is only 750 ms
set-option -g display-time 2000

set -g mouse on
